let config = {
  app_title: "nlist",
  app_description: "Discover curated listings",
  categories: [
    {
      title: "for sale",
      items: [
        { name: "electronics", displayName: "electronics" },
        { name: "Electronics", displayName: "Electronics" },
        { name: "Digital", displayName: "Digital" },
        { name: "Accessories", displayName: "Accessories" },
        { name: "art", displayName: "art" },
        { name: "Art", displayName: "Art" },
        { name: "Crafts", displayName: "Crafts" },
        { name: "crafts", displayName: "crafts" },
        { name: "Furniture", displayName: "Furniture" },
        { name: "Home", displayName: "Home Decor" },
        { name: "Fitness", displayName: "Fitness" },
        { name: "Clothing", displayName: "Clothing" },
        { name: "books", displayName: "books" },
        { name: "Books", displayName: "Books" },
        { name: "Vehicles", displayName: "Vehicles" },
        { name: "Realestate", displayName: "Real Estate" },
        { name: "Entertainment", displayName: "Entertainment" },
        { name: "Pets", displayName: "Pets" },
      ],
    },
    {
      title: "jobs",
      items: [
        { name: "bounties", displayName: "bounties" },
        { name: "contract", displayName: "contract" },
        { name: "full-time", displayName: "full-Time" },
        { name: "internships", displayName: "internships" },
        { name: "applicants", displayName: "looking for a job" },
        { name: "part-time", displayName: "part-Time" },
        { name: "remote", displayName: "remote" },
      ],
    },
    {
      title: "arts and crafts",
      items: [
        { name: "instruments", displayName: "Musical Instruments" },
        { name: "photography", displayName: "Photography" },
        { name: "painting", displayName: "Painting" },
        { name: "sculpture", displayName: "Sculpture" },
        { name: "pottery", displayName: "Pottery" },
      ],
    },
    {
      title: "services",
      items: [
        { name: "automotive", displayName: "automotive" },
        { name: "beauty", displayName: "beauty" },
        { name: "technology", displayName: "technology" },
        { name: "creative", displayName: "creative" },
        { name: "financial", displayName: "financial" },
        { name: "health", displayName: "health" },
        { name: "legal", displayName: "legal" },
        { name: "writing", displayName: "writing" },
      ],
    },
    {
      title: "community",
      items: [
        { name: "artists", displayName: "artists" },
        { name: "classes", displayName: "classes" },
        { name: "events", displayName: "events" },
        { name: "Exchange", displayName: "exchange" },
        { name: "housing", displayName: "housing" },
        { name: "pets", displayName: "pets" },
        { name: "Resale", displayName: "Resale" },
        { name: "rideshare", displayName: "rideshare" },
        { name: "volunteer", displayName: "volunteer" },
      ],
    },
    {
      title: "misc.",
      items: [
        { name: "all", displayName: "EVERYTHING" },
        { name: "gaming", displayName: "gaming" },
        { name: "materials", displayName: "Materials" },
        { name: "wanted", displayName: "Wanted" },
      ],
    },
  ],
};
